version: "2"
volumes:
  ohyes_data: 
    external: true
services:
  ohyes:
    image: "node:19-alpine"
    user: "node"
    restart: "unless-stopped"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - "./:/home/node/app:ro"
      - "ohyes_data:/home/node/app/data:rw"
    command: "npm start"
