version: "2"
services:
  node:
    image: "node:19-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - "./:/home/node/app:ro"
      - "./data:/home/node/app/data"
    command: "npm start"
