export type Format<T = bigint> = { suffix: string, min: T }

export let formats: Format<number>[] = [
  { suffix: " K", min: 1 ** 3 },
  { suffix: " M", min: 1 ** 6 },
  { suffix: " B", min: 1 ** 9 },
  { suffix: " T", min: 1 ** 12 },
  { suffix: " Qd", min: 1 ** 15 },
  { suffix: " Qn", min: 1 ** 18 },
  { suffix: " Sx", min: 1 ** 21 },
  { suffix: " Sp", min: 1 ** 24 },
]

export let sizeFormat: Format<number>[] = [
  { suffix: ' B', min: 1 },
  { suffix: ' KiB', min: 1024 },
  { suffix: ' MiB', min: 1024 ** 2 },
  { suffix: ' GiB', min: 1024 ** 3 },
  { suffix: ' TiB', min: 1024 ** 4 },
]

export let formatsBigint: Format<bigint>[] = [
  { suffix: " K", min: 10n ** 3n },
  { suffix: " M", min: 10n ** 6n },
  { suffix: " B", min: 10n ** 9n },
  { suffix: " T", min: 10n ** 12n },
  { suffix: " Qd", min: 10n ** 15n },
  { suffix: " Qn", min: 10n ** 18n },
  { suffix: " Sx", min: 10n ** 21n },
  { suffix: " Sp", min: 10n ** 24n },
  { suffix: " O", min: 10n ** 27n },
  { suffix: " N", min: 10n ** 30n },
  { suffix: " D", min: 10n ** 33n },
  { suffix: " Ud", min: 10n ** 36n },
  { suffix: " Dd", min: 10n ** 39n },
  { suffix: " Td", min: 10n ** 42n },
  { suffix: " Qdd", min: 10n ** 45n },
  { suffix: " Qnd", min: 10n ** 48n },
  { suffix: " Sxd", min: 10n ** 51n },
  { suffix: " Spd", min: 10n ** 54n },
  { suffix: " Od", min: 10n ** 57n },
  { suffix: " Nd", min: 10n ** 60n },
  { suffix: " Vg", min: 10n ** 63n },
  { suffix: " UVg", min: 10n ** 66n },
  { suffix: " DVg", min: 10n ** 69n },
  { suffix: " TVg", min: 10n ** 72n },
  { suffix: " QdVg", min: 10n ** 75n },
  { suffix: " QnVg", min: 10n ** 78n },
  { suffix: " SxVg", min: 10n ** 81n },
  { suffix: " SpVg", min: 10n ** 84n },
  { suffix: " NVg", min: 10n ** 87n },
  { suffix: " OVg", min: 10n ** 90n },
  { suffix: " Tg", min: 10n ** 93n },
  { suffix: " UTg", min: 10n ** 96n },
  { suffix: " DTg", min: 10n ** 99n },
  { suffix: " TTg", min: 10n ** 102n },
  { suffix: " QdTg", min: 10n ** 105n },
  { suffix: " QnTg", min: 10n ** 108n },
  { suffix: " SxTg", min: 10n ** 111n },
  { suffix: " SpTg", min: 10n ** 114n },
  { suffix: " OTg", min: 10n ** 117n },
  { suffix: " NTg", min: 10n ** 120n },
  { suffix: " QDg", min: 10n ** 123n },
]